apiVersion: v1

kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: "SGVucmlxdWUK"
  PASSWORD: "MTIzCg=="

# Secret is a type of config map, but it is used to store sensitive data with base64 encoding
# But this is not a good practice, because any user can decode the data