apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec: # specification of pod => 1 container by pod (generally)
  containers:
    - name: "goserver"
      image: "henricker/hello-kube-go"
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 150m
          memory: 300Mi
      

# kubectl apply -f k8s/pod.yml 

# Main problem of only work with pod
# => if the pod is down, the application is down
# => Use replicaSet to solve this problem