apiVersion: v1
kind: Service

metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    app: goserver
  type: ClusterIP # generate intern ip => only inside the cluster we can access the service
  ports:
    - port: 80 #port of this service
      targetPort: 80 #port of pod
      name: goserver-service-port
      protocol: TCP

# expose the pod network