apiVersion: v1
kind: Service
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP