apiVersion: v1
kind: Service

metadata:
  name: goserver
  labels:
    app: goserver
spec:
  type: NodePort # create a port on each node of the cluster => we can access the service from outside the cluster
  selector:
    app: goserver
  ports:
    - name: goserver-port
      nodePort: 30001 # 30000> <32767
      port: 80
      targetPort: 80
      protocol: TCP
  

# Node 1  -> 30001 -> port 80 -> pod port 80
# Node 2  -> 30001 -> port 80 -> pod port 80
# Node 3 -> 30001 -> port 80 -> pod port 80

# Acessing any pod with port 30001 we can access the service 